export const nativeOperationIds = [
  "PostIncomingWebhook",
  "ChatPostMessage",
  "ChatUpdate",
  "ChatPostEphemeral",
  "ChatGetPermalinkGet",
  "ChatGetPermalink",
  "ReactionsAdd",
  "ReactionsRemove",
  "ReactionsGetGet",
  "ReactionsGet",
  "AuthTestGet",
  "AuthTest",
  "ConversationsJoin",
  "UsersInfoGet",
  "UsersInfo",
  "UsersLookupByEmailGet",
  "UsersLookupByEmail",
  "FilesInfoGet",
  "FilesInfo",
  "ViewsOpen",
  "AppsConnectionsOpen",
] as const
export type NativeOperationId = (typeof nativeOperationIds)[number]
