import { expect, test } from "bun:test";
import { Database } from "../../../src/index.ts";
import { expectParity } from "../../harness/assert.ts";
import { matrixBoth } from "../../harness/matrix.ts";
import { errorParity, sequenceParity, setupBoth } from "../helpers.ts";
import { sqlstateParity, tempErrorParity } from "../parity-extras.ts";

// CREATE UNLOGGED TABLE, ALTER TABLE ... SET LOGGED | UNLOGGED and pg_class.relpersistence (issue #333).
// The engine has no write-ahead log: the three persistence modes differ only in what the catalog
// reports and in which statements PostgreSQL accepts.
//
// The oracle session is shared across tests and its reset keeps pg_temp, so every temporary
// object here has a name of its own (tmp_sl_*) and is dropped by the test that created it.

/**
 * relpersistence of the named relations. Key constraints have no pg_class index row of their own
 * in every build of the engine, so probes name the relations they compare instead of listing all.
 */
const persistenceOf = (...names: string[]): string =>
  "SELECT c.relname, c.relkind, c.relpersistence FROM pg_class c " +
  `WHERE c.relname IN (${names.map((n) => `'${n}'`).join(", ")}) ORDER BY c.relname`;

// Behavior 1: the statements run and pg_class reflects them.
sequenceParity(
  "relpersistence is p for logged, u for unlogged and t for temporary relations",
  [],
  [
    { sql: "CREATE TABLE logged_kv (id integer, value text)" },
    { sql: "CREATE UNLOGGED TABLE unlogged_kv (id serial, slot integer GENERATED ALWAYS AS IDENTITY, value text)" },
    { sql: "CREATE TEMP TABLE tmp_sl_kv (id integer, value text)" },
    { sql: "CREATE INDEX logged_kv_value ON logged_kv (value)" },
    { sql: "CREATE INDEX unlogged_kv_value ON unlogged_kv (value)" },
    { sql: "CREATE INDEX tmp_sl_kv_value ON tmp_sl_kv (value)" },
    { sql: "CREATE SEQUENCE logged_seq" },
    { sql: "CREATE UNLOGGED SEQUENCE unlogged_seq" },
    { sql: "CREATE TEMP SEQUENCE tmp_sl_seq" },
    { sql: "CREATE VIEW kv_view AS SELECT * FROM logged_kv" },
    { sql: "CREATE MATERIALIZED VIEW kv_mat AS SELECT * FROM logged_kv" },
    { sql: "CREATE UNLOGGED TABLE IF NOT EXISTS unlogged_kv (other integer)" },
    {
      sql: persistenceOf(
        "logged_kv",
        "unlogged_kv",
        "tmp_sl_kv",
        "logged_kv_value",
        "unlogged_kv_value",
        "tmp_sl_kv_value",
        "logged_seq",
        "unlogged_seq",
        "tmp_sl_seq",
        "unlogged_kv_id_seq",
        "unlogged_kv_slot_seq",
        "kv_view",
        "kv_mat",
      ),
      query: true,
    },
    {
      sql: "SELECT table_name, table_type FROM information_schema.tables WHERE table_name IN ('logged_kv', 'unlogged_kv', 'tmp_sl_kv') ORDER BY 1",
      query: true,
    },
    { sql: "DROP TABLE tmp_sl_kv" },
    { sql: "DROP SEQUENCE tmp_sl_seq" },
  ],
);

sequenceParity(
  "CREATE UNLOGGED TABLE AS and LIKE: the new table's own persistence applies",
  ["CREATE UNLOGGED TABLE source_kv (id integer, value text)", "INSERT INTO source_kv VALUES (1, 'a')"],
  [
    { sql: "CREATE UNLOGGED TABLE selected AS SELECT * FROM source_kv" },
    { sql: "CREATE UNLOGGED TABLE renamed (a, b) AS SELECT id, value FROM source_kv" },
    { sql: "CREATE UNLOGGED TABLE shape AS SELECT * FROM source_kv WITH NO DATA" },
    { sql: "CREATE TABLE logged_copy AS SELECT * FROM source_kv" },
    { sql: "CREATE TEMP TABLE tmp_sl_copy AS SELECT * FROM source_kv" },
    { sql: "CREATE TABLE like_copy (LIKE source_kv INCLUDING ALL)" },
    { sql: persistenceOf("selected", "renamed", "shape", "logged_copy", "tmp_sl_copy", "like_copy"), query: true },
    { sql: "SELECT id, value FROM selected", query: true },
    { sql: "DROP TABLE tmp_sl_copy" },
  ],
);

const KV_RELATIONS = persistenceOf("kv", "kv_value_idx", "kv_amount_uq", "kv_serial_seq", "kv_slot_seq", "side_seq");
const KV_CONSTRAINTS =
  "SELECT con.conname, con.contype FROM pg_constraint con JOIN pg_class c ON c.oid = con.conrelid " +
  "WHERE c.relname = 'kv' ORDER BY con.conname";
const KV_ROWS = "SELECT id, value, amount FROM kv ORDER BY id";

sequenceParity(
  "SET UNLOGGED and SET LOGGED keep contents, indexes, constraints and owned sequences",
  [
    `CREATE TABLE kv (
       id integer PRIMARY KEY, value text NOT NULL, amount integer DEFAULT 5 CHECK (amount > 0),
       serial serial, slot integer GENERATED BY DEFAULT AS IDENTITY
     )`,
    "CREATE INDEX kv_value_idx ON kv (value)",
    "CREATE UNIQUE INDEX kv_amount_uq ON kv (amount)",
    "CREATE SEQUENCE side_seq",
    "INSERT INTO kv (id, value, amount) VALUES (1, 'a', 1), (2, 'b', 2)",
  ],
  [
    { sql: KV_RELATIONS, query: true },
    { sql: "ALTER TABLE kv SET UNLOGGED" },
    { sql: KV_RELATIONS, query: true },
    { sql: KV_CONSTRAINTS, query: true },
    { sql: KV_ROWS, query: true },
    {
      sql: "SELECT indexname FROM pg_indexes WHERE tablename = 'kv' AND indexname LIKE 'kv!_%!_%' ESCAPE '!' ORDER BY 1",
      query: true,
    },
    { sql: "INSERT INTO kv (id, value, amount) VALUES (3, 'c', 3)" },
    { sql: "ALTER TABLE kv SET LOGGED" },
    { sql: KV_RELATIONS, query: true },
    { sql: KV_CONSTRAINTS, query: true },
    { sql: KV_ROWS, query: true },
    {
      sql: "SELECT column_name, column_default, is_nullable FROM information_schema.columns WHERE table_name = 'kv' ORDER BY ordinal_position",
      query: true,
    },
  ],
  { compareFinalState: true },
);

const VIOLATIONS: ReadonlyArray<readonly [name: string, sql: string]> = [
  ["the primary key", "INSERT INTO kv (id, value, amount) VALUES (1, 'dup', 9)"],
  ["NOT NULL", "INSERT INTO kv (id, value, amount) VALUES (3, NULL, 9)"],
  ["the CHECK constraint", "INSERT INTO kv (id, value, amount) VALUES (3, 'c', -1)"],
  ["the unique index", "INSERT INTO kv (id, value, amount) VALUES (3, 'c', 2)"],
  ["the foreign key", "INSERT INTO kv (id, value, amount, owner) VALUES (3, 'c', 3, 99)"],
];

for (const target of ["UNLOGGED", "LOGGED"] as const) {
  for (const [name, sql] of VIOLATIONS) {
    errorParity(
      `after SET ${target} the table still enforces ${name}`,
      [
        "CREATE TABLE owners (id integer PRIMARY KEY)",
        "INSERT INTO owners VALUES (1)",
        `CREATE TABLE kv (
           id integer PRIMARY KEY, value text NOT NULL, amount integer CHECK (amount > 0),
           owner integer REFERENCES owners (id)
         )`,
        "CREATE UNIQUE INDEX kv_amount_uq ON kv (amount)",
        "INSERT INTO kv VALUES (1, 'a', 1, 1), (2, 'b', 2, 1)",
        "ALTER TABLE kv SET UNLOGGED",
        ...(target === "LOGGED" ? ["ALTER TABLE kv SET LOGGED"] : []),
      ],
      sql,
      undefined,
      { messageTier: "A" },
    );
  }
}

sequenceParity(
  "sequences owned by the table follow it; a standalone sequence is changed with ALTER SEQUENCE",
  ["CREATE TABLE kv (id serial, value text)", "CREATE SEQUENCE side_seq", "CREATE TEMP SEQUENCE tmp_sl_own_seq"],
  [
    { sql: "ALTER TABLE kv SET UNLOGGED" },
    { sql: "ALTER TABLE kv ADD COLUMN extra bigserial" },
    { sql: persistenceOf("kv", "kv_id_seq", "kv_extra_seq", "side_seq"), query: true },
    { sql: "ALTER SEQUENCE side_seq SET UNLOGGED" },
    { sql: "ALTER SEQUENCE side_seq SET UNLOGGED" },
    { sql: "ALTER SEQUENCE kv_id_seq SET LOGGED" },
    { sql: persistenceOf("kv", "kv_id_seq", "kv_extra_seq", "side_seq"), query: true },
    { sql: "ALTER TABLE kv SET LOGGED" },
    { sql: "ALTER SEQUENCE side_seq SET LOGGED" },
    { sql: "ALTER TABLE side_seq SET UNLOGGED" },
    { sql: persistenceOf("kv", "kv_id_seq", "kv_extra_seq", "side_seq"), query: true },
    { sql: "ALTER SEQUENCE tmp_sl_own_seq SET UNLOGGED" },
    { sql: "ALTER SEQUENCE tmp_sl_own_seq SET LOGGED" },
    { sql: "ALTER SEQUENCE missing_seq SET UNLOGGED" },
    { sql: "ALTER SEQUENCE IF EXISTS missing_seq SET UNLOGGED" },
    { sql: "SELECT nextval('kv_id_seq') AS a, nextval('side_seq') AS b", query: true },
    { sql: "DROP SEQUENCE tmp_sl_own_seq" },
  ],
);

sequenceParity(
  "quoted and schema-qualified tables, ONLY, and combination with other actions",
  [
    "CREATE SCHEMA app",
    'CREATE UNLOGGED TABLE app."Mixed Kv" (id integer, value text)',
    "CREATE TABLE kv (id integer, value text)",
  ],
  [
    { sql: 'ALTER TABLE app."Mixed Kv" SET LOGGED' },
    { sql: 'ALTER TABLE ONLY app."Mixed Kv" SET UNLOGGED' },
    { sql: "ALTER TABLE kv SET unlogged, ALTER COLUMN value SET NOT NULL, ALTER COLUMN value SET STORAGE MAIN" },
    { sql: persistenceOf("Mixed Kv", "kv"), query: true },
    { sql: "INSERT INTO kv VALUES (1, NULL)" },
  ],
);

// Behavior 2: invalid conversions get PostgreSQL's errors.
tempErrorParity(
  "a temporary table cannot be made unlogged",
  ["CREATE TEMP TABLE tmp_sl_to_unlogged (id integer)"],
  "ALTER TABLE tmp_sl_to_unlogged SET UNLOGGED",
  ["DROP TABLE tmp_sl_to_unlogged"],
);

tempErrorParity(
  "a temporary table cannot be made logged",
  ["CREATE TEMP TABLE tmp_sl_to_logged (id integer)"],
  "ALTER TABLE tmp_sl_to_logged SET LOGGED",
  ["DROP TABLE tmp_sl_to_logged"],
);

errorParity(
  "a table referenced by a logged table cannot become unlogged",
  [
    "CREATE TABLE parent (id integer PRIMARY KEY)",
    "CREATE TABLE child (id integer, parent_id integer REFERENCES parent (id))",
  ],
  "ALTER TABLE parent SET UNLOGGED",
  undefined,
  { messageTier: "A" },
);

errorParity(
  "a table referencing an unlogged table cannot become logged",
  [
    "CREATE UNLOGGED TABLE parent (id integer PRIMARY KEY)",
    "CREATE UNLOGGED TABLE child (id integer, parent_id integer REFERENCES parent (id))",
  ],
  "ALTER TABLE child SET LOGGED",
  undefined,
  { messageTier: "A" },
);

sequenceParity(
  "foreign-key pairs convert in dependency order, and a refused conversion changes nothing",
  [
    "CREATE TABLE parent (id integer PRIMARY KEY)",
    "CREATE TABLE child (id integer PRIMARY KEY, parent_id integer REFERENCES parent (id))",
    "INSERT INTO parent VALUES (1)",
    "INSERT INTO child VALUES (10, 1)",
  ],
  [
    { sql: "ALTER TABLE parent SET UNLOGGED" },
    { sql: persistenceOf("parent", "child"), query: true },
    { sql: "ALTER TABLE child SET UNLOGGED" },
    { sql: "ALTER TABLE parent SET UNLOGGED" },
    { sql: persistenceOf("parent", "child"), query: true },
    { sql: "ALTER TABLE child SET LOGGED" },
    { sql: persistenceOf("parent", "child"), query: true },
    { sql: "ALTER TABLE parent SET LOGGED" },
    { sql: "ALTER TABLE child SET LOGGED" },
    { sql: persistenceOf("parent", "child"), query: true },
    { sql: "INSERT INTO child VALUES (11, 2)" },
    { sql: "SELECT id, parent_id FROM child ORDER BY id", query: true },
  ],
  { compareFinalState: true },
);

const FK_SETUP = [
  "CREATE TABLE logged_parent (id integer PRIMARY KEY)",
  "CREATE UNLOGGED TABLE unlogged_parent (id integer PRIMARY KEY)",
  "CREATE TEMP TABLE tmp_sl_parent (id integer PRIMARY KEY)",
  "CREATE TABLE logged_child (parent_id integer)",
  "CREATE UNLOGGED TABLE unlogged_child (parent_id integer)",
  "CREATE TEMP TABLE tmp_sl_child (parent_id integer)",
];
const FK_CLEANUP = ["DROP TABLE IF EXISTS tmp_sl_fk", "DROP TABLE tmp_sl_child", "DROP TABLE tmp_sl_parent"];

const FK_REJECTED: ReadonlyArray<readonly [name: string, sql: string]> = [
  [
    "a logged table referencing an unlogged table",
    "CREATE TABLE c (parent_id integer REFERENCES unlogged_parent (id))",
  ],
  ["a logged table referencing a temporary table", "CREATE TABLE c (parent_id integer REFERENCES tmp_sl_parent (id))"],
  [
    "an unlogged table referencing a temporary table",
    "CREATE UNLOGGED TABLE c (parent_id integer REFERENCES tmp_sl_parent (id))",
  ],
  [
    "a temporary table referencing a logged table",
    "CREATE TEMP TABLE tmp_sl_fk (parent_id integer REFERENCES logged_parent (id))",
  ],
  [
    "a temporary table referencing an unlogged table",
    "CREATE TEMP TABLE tmp_sl_fk (parent_id integer, FOREIGN KEY (parent_id) REFERENCES unlogged_parent (id))",
  ],
  [
    "ADD CONSTRAINT from a logged table to an unlogged table",
    "ALTER TABLE logged_child ADD CONSTRAINT fk FOREIGN KEY (parent_id) REFERENCES unlogged_parent (id)",
  ],
  [
    "ADD CONSTRAINT from an unlogged table to a temporary table",
    "ALTER TABLE unlogged_child ADD FOREIGN KEY (parent_id) REFERENCES tmp_sl_parent (id)",
  ],
  [
    "ADD CONSTRAINT from a temporary table to a logged table",
    "ALTER TABLE tmp_sl_child ADD FOREIGN KEY (parent_id) REFERENCES logged_parent (id)",
  ],
  [
    "ADD COLUMN on a logged table referencing an unlogged table",
    "ALTER TABLE logged_child ADD COLUMN other integer REFERENCES unlogged_parent (id)",
  ],
];

for (const [name, sql] of FK_REJECTED) {
  tempErrorParity(`foreign key rejected: ${name}`, FK_SETUP, sql, FK_CLEANUP);
}

sequenceParity("foreign keys PostgreSQL allows across persistence modes are accepted", FK_SETUP, [
  { sql: "CREATE UNLOGGED TABLE a (parent_id integer REFERENCES logged_parent (id))" },
  { sql: "CREATE UNLOGGED TABLE b (parent_id integer REFERENCES unlogged_parent (id))" },
  { sql: "CREATE TEMP TABLE tmp_sl_fk (parent_id integer REFERENCES tmp_sl_parent (id))" },
  { sql: "ALTER TABLE unlogged_child ADD FOREIGN KEY (parent_id) REFERENCES logged_parent (id)" },
  { sql: "ALTER TABLE logged_child ADD FOREIGN KEY (parent_id) REFERENCES logged_parent (id)" },
  { sql: persistenceOf("a", "b", "tmp_sl_fk", "unlogged_child", "logged_child"), query: true },
  { sql: "ALTER TABLE logged_parent SET UNLOGGED" },
  { sql: "ALTER TABLE logged_child SET UNLOGGED" },
  { sql: "ALTER TABLE logged_parent SET UNLOGGED" },
  { sql: persistenceOf("logged_parent", "logged_child"), query: true },
  ...FK_CLEANUP.map((sql) => ({ sql })),
]);

errorParity(
  "SET UNLOGGED cannot be performed on a view",
  ["CREATE TABLE kv (id integer)", "CREATE VIEW kv_view AS SELECT id FROM kv"],
  "ALTER TABLE kv_view SET UNLOGGED",
  undefined,
  { messageTier: "A" },
);

errorParity(
  "SET LOGGED cannot be performed on a materialized view",
  ["CREATE TABLE kv (id integer)", "CREATE MATERIALIZED VIEW kv_mat AS SELECT id FROM kv"],
  "ALTER TABLE kv_mat SET LOGGED",
  undefined,
  { messageTier: "A" },
);

errorParity("SET UNLOGGED on a missing table", [], "ALTER TABLE missing SET UNLOGGED", "undefined_table", {
  messageTier: "A",
});

errorParity(
  "a real persistence change cannot be followed by another in the same statement",
  ["CREATE TABLE kv (id integer)"],
  "ALTER TABLE kv SET UNLOGGED, SET LOGGED",
  undefined,
  { messageTier: "A" },
);

sequenceParity(
  "a no-op SET followed by a real change is accepted",
  ["CREATE TABLE kv (id integer)"],
  [
    { sql: "ALTER TABLE kv SET LOGGED, SET UNLOGGED" },
    { sql: persistenceOf("kv"), query: true },
    { sql: "ALTER TABLE kv SET UNLOGGED, SET UNLOGGED" },
    { sql: "ALTER TABLE kv SET LOGGED, SET UNLOGGED" },
    { sql: persistenceOf("kv"), query: true },
    { sql: "ALTER TABLE IF EXISTS missing SET UNLOGGED" },
  ],
);

errorParity("views cannot be unlogged", [], "CREATE UNLOGGED VIEW v AS SELECT 1 AS x", undefined, { messageTier: "A" });

errorParity(
  "materialized views cannot be unlogged",
  ["CREATE TABLE kv (id integer)"],
  "CREATE UNLOGGED MATERIALIZED VIEW m AS SELECT id FROM kv",
  undefined,
  { messageTier: "A" },
);

const SYNTAX_ERRORS: ReadonlyArray<readonly [name: string, sql: string]> = [
  ["TEMP UNLOGGED TABLE", "CREATE TEMP UNLOGGED TABLE bad (id integer)"],
  ["UNLOGGED TEMP TABLE", "CREATE UNLOGGED TEMP TABLE bad (id integer)"],
  ["TEMP UNLOGGED SEQUENCE", "CREATE TEMP UNLOGGED SEQUENCE bad"],
  ["UNLOGGED INDEX", "CREATE UNLOGGED INDEX bad ON kv (id)"],
  ["UNLOGGED FUNCTION", "CREATE UNLOGGED FUNCTION bad() RETURNS integer LANGUAGE sql AS 'SELECT 1'"],
];

for (const [name, sql] of SYNTAX_ERRORS) {
  sqlstateParity(`CREATE ${name} is a syntax error`, ["CREATE TABLE kv (id integer)"], sql, "42601");
}

// Behavior 3: repeated reconciliation, rollback and snapshot reload keep the metadata.
sequenceParity(
  "repeating SET UNLOGGED or SET LOGGED is a no-op success",
  ["CREATE TABLE kv (id integer, value text)", "INSERT INTO kv VALUES (1, 'a')"],
  [
    { sql: "ALTER TABLE kv SET LOGGED" },
    { sql: "ALTER TABLE kv SET UNLOGGED" },
    { sql: "ALTER TABLE kv SET UNLOGGED" },
    { sql: persistenceOf("kv"), query: true },
    { sql: "ALTER TABLE kv SET LOGGED" },
    { sql: "ALTER TABLE kv SET LOGGED" },
    { sql: persistenceOf("kv"), query: true },
    { sql: "TRUNCATE kv" },
    { sql: "ALTER TABLE kv SET UNLOGGED" },
    { sql: "TRUNCATE kv" },
    { sql: "ALTER TABLE kv RENAME TO kv_renamed" },
    { sql: persistenceOf("kv", "kv_renamed"), query: true },
  ],
);

sequenceParity(
  "ROLLBACK and ROLLBACK TO SAVEPOINT restore the persistence and the rows",
  [
    "CREATE TABLE kv (id serial, value text)",
    "CREATE INDEX kv_value_idx ON kv (value)",
    "INSERT INTO kv (value) VALUES ('a')",
  ],
  [
    { sql: "BEGIN" },
    { sql: "ALTER TABLE kv SET UNLOGGED" },
    { sql: "INSERT INTO kv (value) VALUES ('b')" },
    { sql: persistenceOf("kv", "kv_value_idx", "kv_id_seq"), query: true },
    { sql: "ROLLBACK" },
    { sql: persistenceOf("kv", "kv_value_idx", "kv_id_seq"), query: true },
    { sql: "SELECT value FROM kv ORDER BY value", query: true },
    { sql: "BEGIN" },
    { sql: "ALTER TABLE kv SET UNLOGGED" },
    { sql: "SAVEPOINT unlogged" },
    { sql: "ALTER TABLE kv SET LOGGED" },
    { sql: persistenceOf("kv", "kv_value_idx", "kv_id_seq"), query: true },
    { sql: "ROLLBACK TO SAVEPOINT unlogged" },
    { sql: persistenceOf("kv", "kv_value_idx", "kv_id_seq"), query: true },
    { sql: "COMMIT" },
    { sql: persistenceOf("kv", "kv_value_idx", "kv_id_seq"), query: true },
    { sql: "BEGIN" },
    { sql: "CREATE UNLOGGED TABLE transient (id integer)" },
    { sql: "CREATE UNLOGGED SEQUENCE transient_seq" },
    { sql: "ROLLBACK" },
    { sql: persistenceOf("transient", "transient_seq"), query: true },
  ],
);

const RELOAD_RELATIONS = persistenceOf(
  "logged_kv",
  "unlogged_kv",
  "converted_kv",
  "tmp_sl_reload",
  "unlogged_kv_value",
  "unlogged_kv_id_seq",
  "converted_kv_id_seq",
  "unlogged_seq",
  "selected",
);

matrixBoth("persistence survives a snapshot reload", async (memory, postgres) => {
  try {
    await setupBoth(memory, postgres, [
      "CREATE TABLE logged_kv (id integer PRIMARY KEY, value text)",
      "CREATE UNLOGGED TABLE unlogged_kv (id serial, value text, parent_id integer REFERENCES logged_kv (id))",
      "CREATE INDEX unlogged_kv_value ON unlogged_kv (value)",
      "CREATE TABLE converted_kv (id serial, value text)",
      "ALTER TABLE converted_kv SET UNLOGGED",
      "CREATE TEMP TABLE tmp_sl_reload (id integer)",
      "CREATE UNLOGGED SEQUENCE unlogged_seq",
      "INSERT INTO logged_kv VALUES (1, 'a')",
      "INSERT INTO unlogged_kv (value, parent_id) VALUES ('u', 1)",
      "CREATE UNLOGGED TABLE selected AS SELECT * FROM unlogged_kv",
    ]);
    memory.restore(memory.snapshot());
    expectParity(await memory.query(RELOAD_RELATIONS), await postgres.query(RELOAD_RELATIONS));
    // the reloaded metadata still drives the conversion rules
    for (const sql of [
      "ALTER TABLE logged_kv SET UNLOGGED",
      "ALTER TABLE unlogged_kv SET LOGGED",
      "ALTER TABLE converted_kv SET LOGGED",
      "CREATE TABLE refused (parent_id integer REFERENCES logged_kv (id))",
    ]) {
      expectParity(await memory.exec(sql), await postgres.exec(sql), { ignoreWriteCounters: true });
    }
    memory.restore(memory.snapshot());
    expectParity(await memory.query(RELOAD_RELATIONS), await postgres.query(RELOAD_RELATIONS));
    const rows = "SELECT id, value, parent_id FROM unlogged_kv";
    expectParity(await memory.query(rows), await postgres.query(rows));
  } finally {
    await postgres.exec("DROP TABLE IF EXISTS tmp_sl_reload");
  }
});

test("a snapshot without unlogged relations carries no persistence metadata", () => {
  const converted = new Database();
  const plain = new Database();
  try {
    for (const db of [converted, plain]) db.exec("CREATE TABLE kv (id serial, value text)");
    converted.exec("ALTER TABLE kv SET UNLOGGED");
    converted.exec("ALTER TABLE kv SET LOGGED");
    // Back to logged is byte-identical to never having been unlogged, which is also
    // what a snapshot written before relpersistence was modelled looks like.
    expect(converted.snapshot().encode()).toEqual(plain.snapshot().encode());
    const reopened = plain.snapshot().open();
    expect(reopened.query("SELECT relpersistence FROM pg_class WHERE relname = 'kv'")).toEqual([
      { relpersistence: "p" },
    ]);
    reopened.close();
  } finally {
    converted.close();
    plain.close();
  }
});
