/**
 * Generates the repo README.md: the overview of Emulates. The catalog of services, including
 * each service's parity, lives on the docs site and in llms.txt. Every word comes from the
 * shared copy (sites/docs/src/lib/content.ts), the published packages' license, and the guides
 * in docs/. Edit those, never README.md.
 *
 *   bun run readme:sync     rewrite README.md
 *   bun run check:readme    fail if README.md is stale (CI)
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import {
  AGENTS,
  CONTRACT,
  FEATURES,
  IDENTITY,
  MARK_REPO_PATH,
  PITCH,
  QUICK_START,
  RISK_DISCLAIMER,
} from "../sites/docs/src/lib/content.ts"
import { guideInfo, sortGuides } from "../sites/docs/src/lib/guides.ts"
import { discoverPackages, REPO, root } from "./release/lib.ts"

const OUT = join(root, "README.md")

if (!existsSync(join(root, MARK_REPO_PATH))) {
  console.error(`::error::missing identity file: ${MARK_REPO_PATH}`)
  process.exit(1)
}
if (!IDENTITY.mark.endsWith(`/${MARK_REPO_PATH}`)) {
  console.error(`::error::IDENTITY.mark must be the main copy of ${MARK_REPO_PATH}`)
  process.exit(1)
}

interface Manifest {
  license?: string
}

const licenses = new Set(
  discoverPackages()
    .filter((p) => p.isPublic)
    .map((p) => (JSON.parse(readFileSync(p.manifestPath, "utf8")) as Manifest).license ?? ""),
)
if (licenses.size !== 1) {
  console.error(
    `::error::published packages disagree on their license: ${[...licenses].join(", ")}`,
  )
  process.exit(1)
}
const [license = "MIT"] = licenses

const guides = sortGuides(
  readdirSync(join(root, "docs"))
    .filter((f) => f.endsWith(".md"))
    .map((f) =>
      guideInfo({ file: f.slice(0, -3), markdown: readFileSync(join(root, "docs", f), "utf8") }),
    ),
)

const cell = (s: string) => s.replace(/\|/g, "\\|")
const badge = (label: string, message: string | number, color: string) =>
  `https://img.shields.io/badge/${encodeURIComponent(label.replace(/-/g, "--").replace(/ /g, "_"))}-${encodeURIComponent(String(message))}-${color}`

const catalog = `${IDENTITY.docs}/services`

const body = [
  "<!-- Generated by scripts/readme.ts from sites/docs/src/lib/content.ts, the published packages' license, and docs/*.md. Edit those, then run `bun run readme:sync`. CI fails when this file is stale. The catalog of services lives on the docs site. -->",
  "",
  '<div align="center">',
  "",
  // Width only. An <img> with both width and height gets GitHub's muted rounded
  // square (js-gh-image-fallback), which shows through the mark's transparent corners.
  `<img src="${IDENTITY.mark}" width="88" alt="">`,
  "",
  `<h1>${IDENTITY.name}</h1>`,
  "",
  `**${IDENTITY.tagline}**`,
  "",
  [
    `[![CI](https://github.com/${REPO}/actions/workflows/pr.yml/badge.svg)](https://github.com/${REPO}/actions/workflows/pr.yml)`,
    `[![License](${badge("license", license, "243f34")})](#license)`,
  ].join(" "),
  "",
  `[Quick start](#quick-start) · [Why](docs/WHY.md) · [Design](docs/DESIGN.md) · [Guides](#guides) · [Catalog](${catalog}) · [llms.txt](llms.txt)`,
  "",
  "</div>",
  "",
  ...(RISK_DISCLAIMER.enabled ? [`> ⚠️ ${RISK_DISCLAIMER.text}`, ""] : []),
  PITCH,
  "",
  `Each emulator is its own npm package. The catalog — names, parity, and what each one covers — is on the [docs site](${catalog}).`,
  "",
  "## Quick start",
  "",
  "```bash",
  `npm install -D ${QUICK_START.package}`,
  "```",
  "",
  "```ts",
  QUICK_START.code,
  "```",
  "",
  `Every package is self-contained ESM with TypeScript types. Every emulator is isomorphic and runs in Node >= 22, Bun >= 1.2, browsers, and Workers. Browse every emulator, with a live playground, on the [docs site](${catalog}).`,
  "",
  `## Why ${IDENTITY.name}`,
  "",
  ...FEATURES.map((f) => `- **${f.title}.** ${f.body}`),
  "",
  "The full rationale, and when not to use it: [docs/WHY.md](docs/WHY.md).",
  "",
  "## One contract for every HTTP service",
  "",
  CONTRACT.intro,
  "",
  "```bash",
  CONTRACT.serve,
  "```",
  "",
  "| Surface | What it gives you |",
  "| --- | --- |",
  ...CONTRACT.rows.map(([surface, detail]) => `| ${cell(surface)} | ${cell(detail)} |`),
  "",
  "```json",
  CONTRACT.config,
  "```",
  "",
  CONTRACT.configNote,
  "",
  "## For coding agents",
  "",
  AGENTS,
  "",
  "## Contributing",
  "",
  "```bash",
  `git clone https://github.com/${REPO}.git && cd emulates`,
  "bun run setup   # install, build every package, create .env.local",
  "bun test",
  "```",
  "",
  "Building, testing and `bun run check` need no secrets and no accounts. Live parity against the real provider sandboxes runs on GitHub Actions with the repo's secrets, so anyone with write access runs it without holding a key: `bun run parity:remote -- <service>`. See [docs/DEVELOPMENT.md](docs/DEVELOPMENT.md) and [docs/SECRETS.md](docs/SECRETS.md).",
  "",
  "## Guides",
  "",
  "| Guide | |",
  "| --- | --- |",
  ...guides.map((g) => `| [${cell(g.title)}](docs/${g.file}.md) | ${cell(g.summary)} |`),
  "",
  "## License",
  "",
  `${license}.`,
  "",
].join("\n")

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : ""
  if (current !== body) {
    console.error(
      "::error::README.md is stale or was edited by hand — edit its sources, then run: bun run readme:sync",
    )
    process.exit(1)
  }
  console.log(`README.md: OK (${guides.length} guides)`)
} else {
  writeFileSync(OUT, body)
  console.log(`README.md: wrote ${guides.length} guides`)
}
