/**
 * Generates the repo README.md. Every word comes from a source the docs site also renders:
 * the shared copy (sites/docs/src/lib/content.ts), each service's package.json `mockingbird`
 * block (category, parity, vendor), and the guides in docs/. Edit those, never README.md.
 *
 *   bun run readme:sync     rewrite README.md
 *   bun run check:readme    fail if README.md is stale (CI)
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { CATEGORIES, type CategorySlug } from "../sites/docs/src/lib/categories.ts"
import {
  AGENTS,
  CONTRACT,
  FEATURES,
  HEADLINE,
  IDENTITY,
  MARK_REPO_PATH,
  PITCH,
  PLATE_REPO_PATH,
  QUICK_START,
  RISK_DISCLAIMER,
} from "../sites/docs/src/lib/content.ts"
import { guideInfo, sortGuides } from "../sites/docs/src/lib/guides.ts"
import { discoverPackages, REPO, root } from "./release/lib.ts"

const OUT = join(root, "README.md")

for (const rel of [MARK_REPO_PATH, PLATE_REPO_PATH]) {
  if (!existsSync(join(root, rel))) {
    console.error(`::error::missing identity file: ${rel}`)
    process.exit(1)
  }
}
if (!IDENTITY.mark.endsWith(`/${MARK_REPO_PATH}`)) {
  console.error(`::error::IDENTITY.mark must be the main copy of ${MARK_REPO_PATH}`)
  process.exit(1)
}

interface Manifest {
  description?: string
  license?: string
  mockingbird?: {
    layer?: string
    category?: string
    displayName?: string
    parity?: string
    vendor?: { website?: string; docs?: string }
  }
}

const services = discoverPackages()
  .filter((p) => p.isPublic)
  .map((p) => ({ pkg: p, manifest: JSON.parse(readFileSync(p.manifestPath, "utf8")) as Manifest }))
  .filter(({ manifest }) => manifest.mockingbird?.layer === "service")
  .map(({ pkg, manifest }) => {
    const meta = manifest.mockingbird ?? {}
    if (
      !meta.displayName ||
      !meta.category ||
      typeof meta.parity !== "string" ||
      meta.parity.trim() === "" ||
      meta.parity.length > 80 ||
      !(meta.category in CATEGORIES)
    ) {
      console.error(
        `::error::${pkg.relDir}/package.json: mockingbird.displayName, .category and .parity (a non-empty string of at most 80 characters) are required`,
      )
      process.exit(1)
    }
    return {
      name: pkg.name,
      dir: pkg.relDir,
      displayName: meta.displayName,
      category: CATEGORIES[meta.category as CategorySlug].label,
      parity: meta.parity,
      description: (manifest.description ?? "").replace(/\s+/g, " ").trim(),
      website: meta.vendor?.website ?? null,
      docs: meta.vendor?.docs ?? null,
    }
  })
  .sort((a, b) => a.displayName.localeCompare(b.displayName))

const licenses = new Set(
  discoverPackages()
    .filter((p) => p.isPublic)
    .map((p) => (JSON.parse(readFileSync(p.manifestPath, "utf8")) as Manifest).license ?? ""),
)
if (licenses.size !== 1) {
  console.error(
    `::error::published packages disagree on their license: ${[...licenses].join(", ")}`,
  )
  process.exit(1)
}
const [license = "MIT"] = licenses

const guides = sortGuides(
  readdirSync(join(root, "docs"))
    .filter((f) => f.endsWith(".md"))
    .map((f) =>
      guideInfo({ file: f.slice(0, -3), markdown: readFileSync(join(root, "docs", f), "utf8") }),
    ),
)

const cell = (s: string) => s.replace(/\|/g, "\\|")
const badge = (label: string, message: string | number, color: string) =>
  `https://img.shields.io/badge/${encodeURIComponent(label.replace(/-/g, "--").replace(/ /g, "_"))}-${encodeURIComponent(String(message))}-${color}`

const vendorLinks = (s: { website: string | null; docs: string | null }) =>
  [
    s.website && `[${new URL(s.website).hostname.replace(/^www\./, "")}](${s.website})`,
    s.docs && `[API docs](${s.docs})`,
  ]
    .filter(Boolean)
    .join(" · ")

const serviceTable = () => {
  const rows = services.map(
    (s) =>
      `| [${cell(s.displayName)}](${s.dir}) | ${vendorLinks(s)} | ${cell(s.category)} | [\`${s.name}\`](https://www.npmjs.com/package/${s.name}) | ${cell(s.parity)} | ${cell(s.description)} |`,
  )
  return [
    "| Service | Vendor | Category | Package | Parity | What it mocks |",
    "| --- | --- | --- | --- | --- | --- |",
    ...rows,
  ]
}

const body = [
  "<!-- Generated by scripts/readme.ts from sites/docs/src/lib/content.ts, packages/service/*/package.json and docs/*.md. Edit those, then run `bun run readme:sync`. CI fails when this file is stale. -->",
  "",
  '<div align="center">',
  "",
  // Width only. An <img> with both width and height gets GitHub's muted rounded
  // square (js-gh-image-fallback), which shows through the mark's transparent corners.
  `<img src="${IDENTITY.mark}" width="88" alt="">`,
  "",
  `<h1>${IDENTITY.name}</h1>`,
  "",
  `**${HEADLINE.lead} ${HEADLINE.accent}**`,
  "",
  IDENTITY.note,
  "",
  [
    `[![Services](${badge("Services", services.length, "243f34")})](#services)`,
    `[![CI](https://github.com/${REPO}/actions/workflows/pr.yml/badge.svg)](https://github.com/${REPO}/actions/workflows/pr.yml)`,
    `[![License](${badge("license", license, "243f34")})](#license)`,
  ].join(" "),
  "",
  "[Quick start](#quick-start) · [Services](#services) · [Why](docs/WHY.md) · [Design](docs/DESIGN.md) · [Guides](#guides) · [llms.txt](llms.txt)",
  "",
  "</div>",
  "",
  ...(RISK_DISCLAIMER.enabled ? [`> ⚠️ ${RISK_DISCLAIMER.text}`, ""] : []),
  PITCH,
  "",
  "## Quick start",
  "",
  "```bash",
  `npm install -D ${QUICK_START.package}`,
  "```",
  "",
  "```ts",
  QUICK_START.code,
  "```",
  "",
  "Every package is self-contained ESM with TypeScript types. Every mock is isomorphic and runs in Node >= 22, Bun >= 1.2, browsers, and Workers. To open a live playground, run the docs site: `bun docs`.",
  "",
  "## Why Mockingbird",
  "",
  ...FEATURES.map((f) => `- **${f.title}.** ${f.body}`),
  "",
  "The full rationale, and when not to use it: [docs/WHY.md](docs/WHY.md).",
  "",
  "## Services",
  "",
  `${services.length} services, each its own npm package. Every service declares the parity it keeps with its vendor.`,
  "",
  ...serviceTable(),
  "",
  "Operation coverage per service is in each package's `SUPPORT.md` (or `COMPATIBILITY.md` for the SQL engines), and on the docs site's coverage page.",
  "",
  "## One contract for every HTTP service",
  "",
  CONTRACT.intro,
  "",
  "```bash",
  CONTRACT.serve,
  "```",
  "",
  "| Surface | What it gives you |",
  "| --- | --- |",
  ...CONTRACT.rows.map(([surface, detail]) => `| ${cell(surface)} | ${cell(detail)} |`),
  "",
  "```json",
  CONTRACT.config,
  "```",
  "",
  CONTRACT.configNote,
  "",
  "## For coding agents",
  "",
  AGENTS,
  "",
  "## Contributing",
  "",
  "```bash",
  `git clone https://github.com/${REPO}.git && cd mockingbird`,
  "bun run setup   # install, build every package, create .env.local",
  "bun test",
  "```",
  "",
  "Building, testing and `bun run check` need no secrets and no accounts. Live parity against the real provider sandboxes runs on GitHub Actions with the repo's secrets, so anyone with write access runs it without holding a key: `bun run parity:remote -- <service>`. See [docs/DEVELOPMENT.md](docs/DEVELOPMENT.md) and [docs/SECRETS.md](docs/SECRETS.md).",
  "",
  "## Guides",
  "",
  "| Guide | |",
  "| --- | --- |",
  ...guides.map((g) => `| [${cell(g.title)}](docs/${g.file}.md) | ${cell(g.summary)} |`),
  "",
  "## License",
  "",
  `${license}.`,
  "",
].join("\n")

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : ""
  if (current !== body) {
    console.error(
      "::error::README.md is stale or was edited by hand — edit its sources, then run: bun run readme:sync",
    )
    process.exit(1)
  }
  console.log(`README.md: OK (${services.length} services, ${guides.length} guides)`)
} else {
  writeFileSync(OUT, body)
  console.log(`README.md: wrote ${services.length} services, ${guides.length} guides`)
}
