import { errorParity, sequenceParity } from "../helpers.ts";

const setup = ['CREATE SCHEMA geviti', 'CREATE TABLE geviti."profileStates" (seq bigint NOT NULL)'];
const addDumpIdentity = `
  ALTER TABLE geviti."profileStates"
    ALTER COLUMN seq ADD GENERATED ALWAYS AS IDENTITY (
      SEQUENCE NAME geviti."profileStates_seq_seq"
      START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    )
`;

sequenceParity("pg_dump identity sequence options execute", setup, [{ sql: addDumpIdentity }]);

errorParity(
  "ADD IDENTITY requires the existing column to be NOT NULL",
  ["CREATE TABLE nullable_identity (seq bigint)"],
  "ALTER TABLE nullable_identity ALTER COLUMN seq ADD GENERATED ALWAYS AS IDENTITY",
);

sequenceParity("named identity sequence generates consecutive values", setup, [
  { sql: addDumpIdentity },
  { sql: 'INSERT INTO geviti."profileStates" DEFAULT VALUES' },
  { sql: 'INSERT INTO geviti."profileStates" DEFAULT VALUES' },
  { sql: 'SELECT seq FROM geviti."profileStates" ORDER BY seq', query: true },
]);

sequenceParity("named identity sequence is catalog-visible", setup, [
  { sql: addDumpIdentity },
  {
    sql: `SELECT pg_get_serial_sequence('geviti."profileStates"', 'seq') AS sequence_name`,
    query: true,
  },
  {
    sql: `
      SELECT n.nspname, c.relname, c.relkind
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = 'geviti' AND c.relname = 'profileStates_seq_seq'
    `,
    query: true,
  },
  {
    sql: `
      SELECT is_identity
      FROM information_schema.columns
      WHERE table_schema = 'geviti' AND table_name = 'profileStates' AND column_name = 'seq'
    `,
    query: true,
  },
]);

sequenceParity(
  "quoted identity sequence names honor bounds, cache, and cycle options",
  ['CREATE SCHEMA "AppSchema"', 'CREATE TABLE "AppSchema"."MixedTable" (seq bigint NOT NULL)'],
  [
    {
      sql: `
        ALTER TABLE "AppSchema"."MixedTable"
          ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME "AppSchema"."MixedSequence"
            START WITH 2 INCREMENT BY 2 MINVALUE 2 MAXVALUE 4 CACHE 1 CYCLE
          )
      `,
    },
    { sql: 'INSERT INTO "AppSchema"."MixedTable" DEFAULT VALUES' },
    { sql: 'INSERT INTO "AppSchema"."MixedTable" DEFAULT VALUES' },
    { sql: 'INSERT INTO "AppSchema"."MixedTable" DEFAULT VALUES' },
    { sql: 'INSERT INTO "AppSchema"."MixedTable" (seq) VALUES (99)' },
    { sql: 'SELECT seq FROM "AppSchema"."MixedTable"', query: true },
  ],
);
